sudo: false

language: node_js

cache:
  directories:
    - node_modules

node_js:
  - 'stable'
  - '5.4.1'
  - '5.4.0'
  - '5.3.0'
  - '5.2.0'
  - '5.1.1'
  - '0.12'

before_install:
  - npm config set progress=false
  - npm install -g typings
  - npm typings install

before_script:
  - npm prune

script:
  - npm run test:all
